apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - redis.yaml
  - timescaledb.yaml
  - orchestrator.yaml
  - worker.yaml
  - worker-hpa.yaml
  - dashboard.yaml
  - prometheus.yaml
  - grafana.yaml